name: ezoneapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0
  provider: ^6.1.2
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.2
  # whatsapp_share: ^2.0.2
  # share: ^2.0.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^1.2.2
  barcode_scan2: ^4.3.3
  sqflite: ^2.4.0

  #flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png

